---
title: "'List Before Last: All 2 Cues' Performance Analysis"
author: "Will Hopper"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_caption: yes
    toc: true
    toc_depth: 2
    css: custom.css
vignette: >
  %\VignetteIndexEntry{LB4L2: All 2 Cues}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
<style>

img {
  padding: 10px;
  border-bottom: 2px solid #000;
}

</style>
```{r setup, include=FALSE}
library(FAM)
library(dplyr)
library(whoppeR)
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r tests, include=FALSE, eval=FALSE}
## accuracy as IV 
IV_acc <- summary(LB4L2_final, level = "group")
IV_acc_sub <- summary(LB4L2_final, level = "subject")
CD_acc <- summary(LB4L2_final, level = "group", given_practice = TRUE)
raw_CD_acc <- summary(LB4L2_final, level = "raw", given_practice = TRUE)
raw_joint_acc <- summary(LB4L2_final, level = "raw", given_practice = TRUE, given_final = TRUE)
identical(summary(LB4L2_final, level = "group", given_practice = 1:2), CD_acc)
CD_acc_1 <- summary(LB4L2_final, level = "group", given_practice = 1)
CD_acc_2 <- summary(LB4L2_final, level = "group", given_practice = 2)
joint_acc <- summary(LB4L2_final, level = "group", given_practice = TRUE, given_final = TRUE)
joint_acc_1 <- summary(LB4L2_final, level = "group", given_practice = 1, given_final = TRUE)
joint_acc_2 <- summary(LB4L2_final, level = "group", given_practice = 2, given_final = TRUE)

# RT as DV
IV_RT <- summary(LB4L2_final, level= "group", DV = "RT", given_final = FALSE)
IV_RT_sub <- summary(LB4L2_final, level= "subject", DV = "RT", given_final = FALSE)
CD_RT <- summary(LB4L2_final, level = "group", DV = "RT")
CD_RT_sub <- summary(LB4L2_final, level = "subject", DV = "RT")
CD_RT_prac <- summary(LB4L2_final, level = "group", DV = "RT", given_practice = TRUE)
identical( summary(LB4L2_final, level = "group", DV = "RT", given_practice = 1:2), CD_RT_prac)
CD_RT_prac1 <- summary(LB4L2_final, level = "group", DV = "RT", given_practice = 1)
CD_RT_prac2 <- summary(LB4L2_final, level = "group", DV = "RT", given_practice = 2)
```


## Accuracy and RT by Experimental Condition
```{r IV, fig.align='center', fig.width = 9}
IV_acc <- summary(LB4L2_final, level = "group")
autoplot(IV_acc) + 
  theme_larger(2)
IV_RT <- summary(LB4L2_final, level= "group", DV = "RT", given_final = FALSE)
autoplot(IV_RT) + 
  theme_larger(2)
```


## Conditional Accuracy and RT
```{r conditionals, fig.align='center', fig.width = 9}
CD_acc <- summary(LB4L2_final, level = "group", given_practice = 1)
autoplot(CD_acc) + 
  theme_larger(2)
CD_final_RT <- summary(LB4L2_final, level= "group", DV = "RT")
autoplot(CD_final_RT) + 
  theme_larger(2)
```

## Joint Accuracy and RT
```{r joint, fig.align='center', warning=FALSE, fig.width = 9}
joint_acc_prac1 <- summary(LB4L2_final, level = "group", given_practice = 1, given_final = TRUE)
joint_acc_prac1$cell = interaction(joint_acc_prac1$practice1acc, joint_acc_prac1$final_acc)
lookup_table <- c("1.1" ="+ / +", "1.0"  =  "+ / -", "0.1"  = "- / +", "0.0" = "- / -")

ggplot(joint_acc_prac1, aes(x = group, y= probability, color = sameCue, group = sameCue)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
  facet_grid(~cell,labeller = labeller(cell = lookup_table)) + 
  scale_color_discrete("Cue Used", breaks = c("no","yes"),
                       labels = c(no = "Other Cue", yes ="Same Cue")) +
  scale_x_discrete("Group",expand=c(0,.25),
                 limits = c("immediate", "delay"),
                 labels=c("Immediate","Delay")) +
  theme_larger(1.75) + 
  ggtitle('Joint Distribution of Practice and Final Test Outcomes')

raw_joint_RT_prac1  <- summary(LB4L2_final, level= "raw", DV = "RT",
                                given_practice = 1, given_final = TRUE)
raw_joint_RT_prac1$cell = interaction(raw_joint_RT_prac1$practice1acc,
                                      raw_joint_RT_prac1$final_acc)

ggplot(raw_joint_RT_prac1, aes(x = practice1RT, y= final_RT, color = group)) + 
  geom_point(size = 3, alpha = .4) + 
  geom_smooth(se = FALSE, na.rm = TRUE, method = "lm") + 
  facet_wrap(~cell,labeller = labeller(cell = lookup_table)) + 
  ylab("Final Test First-Press Latency") + 
  xlab("Practice Test First-Press Latency") + 
  theme_larger(1.75) + 
  ggtitle('Joint Distribution of Practice and Final Test Outcomes')

ggplot(raw_joint_RT_prac1, aes(x = practice1RT, y= final_RT - practice1RT, color = group)) + 
  geom_point(size = 3, alpha = .4) + 
  facet_wrap(~cell,labeller = labeller(cell = lookup_table)) + 
  ylab("Final - Practice Test F.P. Latency") + 
  xlab("Practice Test First-Press Latency") + 
  theme_larger(1.75) + 
  ggtitle('Difference in RT across Practice & Final Test Outcomes')

```
