#' LBL42 PCR
#'
#' Implementation of the PCR model of LB4L2 experiment
#' @param PCR_model_obj A PCRparams object, as generated by \code{initPCR}
#' @param groups A numeric scalar indicating how many independtn groups to
#' make predictions for
#'
#' @return A list of PCR objects, with as many elements as there are \code{groups}.
#' Each list element holds the PCR objects created for each condition.
#'
#' @import PCR
#' @export
#'
#' @examples
#' model_params <- initPCR(params = list(ER=.6, LR=.2, FR=.1, TR=.15, TV = .05),
#'                    distribution = "beta", nItems = 20, nSims = 1000,
#'                    nFeatures = 100, time = 10)
#' results <- LB4L2_PCR(model_params)
#'
LB4L2_PCR <- function(PCR_model_obj, groups = 1, ...) {

  stopifnot(is.finite(groups) && groups > 0)
  results <- vector (mode = "list", length = groups)

  control <- study(PCR_model_obj, nCues = 1, tests_per_cue = 1) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  SC_study <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(1,0)) %>%
    study(cue = 1) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  OC_study <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(1,0)) %>%
    study(cue = 2) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  SC_test <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(2,0)) %>%
    cuedRecall(cue = 1) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  OC_test <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(1,1)) %>%
    cuedRecall(cue = 2) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  results[[1]] <- list("SC_test" = SC_test, "SC_study" = SC_study,
                       "OC_test" = OC_test, "OC_study" = OC_study,
                       "control" = control)
  class(results[[1]]) <- c("LB4L2_PCR")
  done <- 1
  while (done < groups) {
    x <- update(PCR_model_obj, list(FR = PCR_model_obj$params[[paste0("FR",done+1)]]))
    results[done + 1]<- LB4L2_PCR(x, groups = 1)
    class(results[[done + 1]]) <- c("LB4L2_PCR", class(results))
    done <- done + 1
    if (done == length(results)) {
      results <- setNames(results, paste0("group",1:groups))
    }

  }

  return(results)

}

#' @export
#' @importFrom tidyr separate
#' @importFrom tidyr gather
summary.LB4L2_PCR <- function(x, DV = "recalled") {

  IVresults <- bind_rows(lapply(x, summary), .id = "condition") %>%
    mutate(practice = toupper(substr(practice,1,1)))

  practice_test <- filter(IVresults, practice == "T", test == 1) %>%
    mutate(sameCue = ifelse(grepl("OC", condition), "no", "yes"))

  final_test <- anti_join(IVresults,practice_test,
                          by = c("condition","practice","test")) %>%
    group_by(condition) %>%
    mutate(OCpractice = switch(first(condition),
                               OC_test = "T",
                               OC_study = "S",
                               "N")) %>%
    ungroup()

  # Subset all the data from items tested twice.
  SC_test <- x[["SC_test"]]$recalled[[1]]
  SC_joint <- mapply(`&`,
                     list(cor_inc = SC_test[,,1], inc_inc = !SC_test[,,1],
                          cor_cor = SC_test[,,1], inc_cor = !SC_test[,,1]),
                     list(!SC_test[,,2], !SC_test[,,2], SC_test[,,2], SC_test[,,2]))

  OC_tp <- x[["OC_test"]]$recalled$Cue2
  OC_final <- x[["OC_test"]]$recalled$Cue1
  OC_joint <- mapply(`&`,
                    list(cor_inc = OC_tp, inc_inc = !OC_tp,
                         cor_cor = OC_tp, inc_cor = !OC_tp),
                    list(!OC_final, !OC_final, OC_final, OC_final))

  ## Joint Accuracy Results
  SC_joint_acc <- colMeans(SC_joint)
  OC_joint_acc <- colMeans(OC_joint)

  ## Joint RT results
  LU_table <- list(joint_outcome = c(cor_inc = "1_0", inc_inc = "0_0",
                                     cor_cor = "1_1",  inc_cor = "0_1"))
  raw_joint_RT <- list(OC_joint_RT = apply(OC_joint, 2,
                                           function(j) {
                                             sapply(rev(x[['OC_test']]$RT), `[`, j)
                                           }),
                       SC_joint_RT = apply(SC_joint, 2,
                                           function(j) {
                                             apply(x[['SC_test']]$RT$Cue1, 3, `[`,j)
                                           })) %>%
    lapply(function(x) {
      lapply(x, function(y) {
        as.data.frame(`dimnames<-`(y, list(NULL, c("practiceRT", "finalRT"))))
        })
      }) %>%
    lapply(bind_rows, .id = "joint_outcome") %>%
    bind_rows(.id = "condition") %>%
    mutate(condition = ifelse(condition == "SC_joint_RT", "yes", "no"),
           joint_outcome = LU_table$joint_outcome[joint_outcome]) %>%
    rename(sameCue = condition) %>%
    separate(joint_outcome, c("practice", "final")) %>%
    mutate_each('as.numeric', practice,final) %>%
    group_by(sameCue, practice, final) %>%
    summarise(rawRTs = list(matrix(c(practiceRT,finalRT),ncol=2,
                                   dimnames = list(NULL, c("practiceRT", "finalRT"))))
              )

  joint_results <- cbind(as.data.frame(SC_joint_acc),
                         as.data.frame(OC_joint_acc)) %>%
    mutate(condition = rownames(.)) %>%
    separate(condition, c("practice", "final")) %>%
    mutate(practice = ifelse(practice == "cor", 1, 0),
           final = ifelse(final == "cor", 1, 0)) %>%
    gather(sameCue, probability, SC_joint_acc, OC_joint_acc) %>%
    mutate(sameCue = ifelse(sameCue == "SC_joint_acc", "yes", "no")) %>%
    left_join(y = raw_joint_RT, by = c("sameCue", "practice", "final")) %>%
    tbl_df()

  # Conditional Accuracy
  SC_CD <- SC_joint_acc[c("cor_cor", "inc_cor")]/abs((c(0,1) - practice_test$accuracy[practice_test$sameCue=="yes"]))
  OC_CD <- OC_joint_acc[c("cor_cor", "inc_cor")]/abs((c(0,1) - practice_test$accuracy[practice_test$sameCue=="no"]))

  CD_results <- cbind(as.data.frame(SC_CD), as.data.frame(OC_CD)) %>%
    mutate(practice = gsub("_cor", "", rownames(.))) %>%
    gather(sameCue, accuracy, SC_CD, OC_CD) %>%
    mutate(sameCue = ifelse(sameCue == "SC_CD", "yes", "no")) %>%
    mutate(sameCue, practice, accuracy)

  return(list(practice= practice_test, final = final_test,
              conditional = CD_results, joint = joint_results))
}

#' fitPCR
#'
#' @param PCRparams_obj
#' @param objective_fcn E.g., LB4L2_PCR
#' @param error_fcn
#' @param ...
#'
#' @return
#'
#' @import PCR
#' @export
#'
#' @examples

fitPCR <- function(free_parameters, PCRparams_obj, objective_fcn, error_fcn, ...) {

  PCRparams_obj <- update(PCRparams_obj, as.list(free_parameters))
  acc_param_vals <- PCRparams_obj$params[names(PCRparams_obj$params) %in% c("ER","LR","FR","FR2","TR","space","TC")]
  RT_param_vals <- PCRparams_obj$params[c("Tmin", "Tmax", "lambda")]

  if (any(sapply(acc_param_vals, function(x) x <= 0.01 || x >= .99))) {
    return(1000000)
  }

  if (any(sapply(RT_param_vals, function(x) x <= 0))) {
    return(1000000)
  }

  if (RT_param_vals$Tmin > RT_param_vals$Tmax) {
    return(1000000)
  }

  raw <- objective_fcn(PCRparams_obj, groups = list(...)$group)
  if (length(raw) > 1) {
    results <- lapply(raw, summary)
    results <- do.call(mapply, c(list(FUN = bind_rows), results , list(.id = "group")))
  } else {
    results <- summary(raw)
  }

  error <- error_fcn(results, ...)
  return(error$error)

}

#' LB4L2_PCR Error Function
#'
#' @param results
#' @param IV_obs
#' @param joint_obs
#' @param likelihood
#'
#' @return
#'
#' @import PCR
#' @importFrom tidyr gather spread unnest
#' @importFrom ks kde
#' @importFrom whoppeR binomialLL multinomialLL
#' @export
#'
#' @examples
LB4L2_PCR_erf <- function(results, IV_obs, joint_obs, likelihood = c("RT","accuracy","all"), ...) {

  likelihood <- match.arg(likelihood,  c("RT","accuracy","all"))
  error <- 0

  IV_pred <- results$final %>%
    select(group, practice, OCpractice, final_acc = accuracy,
           mean_p = proportion, mean_RT = medianRT, rawRTs) %>%
    mutate(group = ifelse(group == "group1", "immediate", "delay"))

  IV_RT <- inner_join(select(IV_obs, group:final_acc, rawRTs, subject),
                      select(IV_pred, group:final_acc, rawRTs),
                      by = c("group", "practice", "OCpractice", "final_acc")) %>%
    rename(obs = rawRTs.x, pred = rawRTs.y)

  p_complete <- IV_RT %>%
    select(-obs) %>%
    filter(final_acc == 1) %>%
    group_by_(.dots = setdiff(names(.), "pred")) %>%
    summarise(p_complete =  mean(pexp(8 - pred[[1]], rate = 1)))

  IV_acc <- inner_join(select(IV_obs, group:mean_p, subject),
                       select(IV_pred, group:mean_p),
                       by = c("group", "practice", "OCpractice", "final_acc")) %>%
    rename(obs = mean_p.x, pred = mean_p.y) %>%
    left_join(p_complete, by = c("group","practice","OCpractice","final_acc","subject")) %>%
    mutate(pred = pred * p_complete)

  ## joint probabilities section ##
  conditional_vars <- grep("*acc$", names(joint_obs), value=TRUE)

  J_pred <- results$joint %>%
    select(group, sameCue, practice1acc = practice, final_acc = final,
           joint_p = probability, rawRTs) %>%
    mutate(group = ifelse(group == "group1", "immediate", "delay"))

  J_RT <- inner_join(select(joint_obs, group:final_acc, rawRTs, subject),
                     select(J_pred, group:final_acc, rawRTs),
                     by = c("group","sameCue", conditional_vars)) %>%
    rename(obs = rawRTs.x, pred = rawRTs.y)

  # This finds the probability that each RT from the [correct, correct] condition
  # completes in 8 seconds. Then it multiplies those two together for the joint probability
  # that they both complete in less than 8 seconds. Those probabilities are then averaged.
  p_complete <- J_RT %>%
    select(-obs) %>%
    filter(!is.null(pred)) %>%
    group_by_(.dots = setdiff(names(.), "pred")) %>%
    summarise(p_complete =  mean(apply((pexp(8 - pred[[1]])),1,prod)))

  J_acc <- inner_join(select(joint_obs, group:joint_p, subject),
                      select(J_pred, group:joint_p),
                      by = c("group","sameCue", conditional_vars))%>%
    rename(obs = joint_p.x, pred = joint_p.y) %>%
    left_join(p_complete, by = c("group","sameCue",conditional_vars,"subject")) %>%
    mutate(pred = pred * p_complete)

  if (likelihood %in% c("all","accuracy")) {

    IV_acc_lik <- IV_acc %>%
      filter(final_acc ==1, (practice != "T" & OCpractice != "T")) %>%
      with(binomialLL(obs = obs, pred = pred, N = 20))

    J_acc_lik <- J_acc %>%
      filter(!is.na(pred)) %>%
      mutate(pred = replace(pred, pred==0, .Machine$double.xmin)) %>%
      with(multinomialLL(obs, pred, N = 20))

    error <- error + IV_acc_lik + multinomial_lik
  }

  if (likelihood %in% c("all","RT")) {

    IV_RT_lik <- IV_RT %>%
      filter(final_acc ==1, (practice != "T" & OCpractice != "T")) %>%
      rowwise() %>%
      mutate(lik = list(sapply(obs,
                               function(x,y) { sum(dexp(Filter(function(z) {z>=0}, x-y))) },
                               y=pred)))
    J_RT_lik <- J_RT %>%
      filter(!is.null(obs)) %>%
      rowwise() %>%
      mutate(lik = list(apply(obs, 1,
                              function(x,y) {
                                a <- x-y
                                a <- a[a[,1]>=0 & a[,2]>=0,]
                                sum(apply(a, 1, function(z) prod(dexp(z, rate =1))))
                              },
                              y=pred)))
    error <- error + sum(unlist(IV_RT_lik$lik)) + sum(unlist(J_RT_lik$lik))
  }
  return(list(error = error))
}

#' @export
#'
combine <- function(obj, practice = NA, final = NA, conditional = NA, joint = NA) {

}
