#' LBL42 PCR
#'
#' Implementation of the PCR model of LB4L2 experiment
#' @param PCR_model_obj A PCRparams object, as generated by \code{initPCR}
#' @param groups A numeric scalar indicating how many independtn groups to
#' make predictions for
#'
#' @return A list of PCR objects, with as many elements as there are \code{groups}.
#' Each list element holds the PCR objects created for each condition.
#'
#' @import PCR
#' @export
#'
#' @examples
#' model_params <- initPCR(params = list(ER=.6, LR=.2, FR=.1, TR=.15, TV = .05),
#'                    distribution = "beta", nItems = 20, nSims = 1000,
#'                    nFeatures = 100, time = 10)
#' results <- LB4L2_PCR(model_params)
#'
LB4L2_PCR <- function(PCR_model_obj, groups = 1, ...) {

  stopifnot(is.finite(groups) && groups > 0)
  results <- vector (mode = "list", length = groups)

  control <- study(PCR_model_obj, nCues = 1, tests_per_cue = 1) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  SC_study <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(1,0)) %>%
    study(cue = 1) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  OC_study <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(1,0)) %>%
    study(cue = 2) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  SC_test <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(2,0)) %>%
    cuedRecall(cue = 1) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  OC_test <- study(PCR_model_obj, nCues = 2, tests_per_cue = c(1,1)) %>%
    cuedRecall(cue = 2) %>%
    forget(cue = 1) %>%
    thresh_change() %>%
    cuedRecall(cue = 1, increment = FALSE)

  results[[1]] <- list("SC_test" = SC_test, "SC_study" = SC_study,
                       "OC_test" = OC_test, "OC_study" = OC_study,
                       "control" = control)
  class(results[[1]]) <- c("LB4L2_PCR")
  done <- 1
  while (done < groups) {
    x <- update(PCR_model_obj, list(FR = PCR_model_obj$params[[paste0("FR",done+1)]]))
    results[done + 1]<- LB4L2_PCR(x, groups = 1)
    class(results[[done + 1]]) <- c("LB4L2_PCR", class(results))
    done <- done + 1
    if (done == length(results)) {
      results <- setNames(results, paste0("group",1:groups))
    }

  }

  return(results)

}

#' @export
#' @importFrom tidyr separate
#' @importFrom tidyr gather
summary.LB4L2_PCR <- function(x, DV = "recalled") {

  IVresults <- bind_rows(lapply(x, summary), .id = "condition") %>%
    mutate(practice = toupper(substr(practice,1,1)))

  practice_test <- filter(IVresults, practice == "T", test == 1) %>%
    mutate(sameCue = ifelse(grepl("OC", condition), "no", "yes"))

  final_test <- anti_join(IVresults,practice_test,
                          by = c("condition","practice","test")) %>%
    group_by(condition) %>%
    mutate(OCpractice = switch(first(condition),
                               OC_test = "T",
                               OC_study = "S",
                               "N")) %>%
    ungroup()

  # Subset all the data from items tested twice.
  SC_test <- x[["SC_test"]]$recalled[[1]]
  SC_joint <- mapply(`&`,
                     list(cor_inc = SC_test[,,1], inc_inc = !SC_test[,,1],
                          cor_cor = SC_test[,,1], inc_cor = !SC_test[,,1]),
                     list(!SC_test[,,2], !SC_test[,,2], SC_test[,,2], SC_test[,,2]))

  OC_tp <- x[["OC_test"]]$recalled[[2]]
  OC_final <- x[["OC_test"]]$recalled[[1]]
  OC_joint <- mapply(`&`,
                    list(cor_inc = OC_tp, inc_inc = !OC_tp,
                         cor_cor = OC_tp, inc_cor = !OC_tp),
                    list(!OC_final, !OC_final, OC_final, OC_final))

  ## Joint Accuracy Results
  SC_joint_acc <- colMeans(SC_joint)
  OC_joint_acc <- colMeans(OC_joint)

  ## Joint RT results
  raw_joint_RT <- list(OC_joint_RT = sapply(x[['OC_test']]$RT, `[`, OC_joint[,"cor_cor"]),
                       SC_joint_RT = apply(x[['SC_test']]$RT[[1]], 3, `[`, SC_joint[,"cor_cor"])) %>%
    lapply(`dimnames<-`, (list(NULL, c("practice", "final")))) %>%
    mutate(tbl_df(data.frame(sameCue = c("no","yes"), practice = 1, final =1)),
           raw_joint_RTs = .)

  joint_results <- cbind(as.data.frame(SC_joint_acc), as.data.frame(OC_joint_acc)) %>%
    mutate(condition = rownames(.)) %>%
    separate(condition, c("practice", "final")) %>%
    mutate(practice = ifelse(practice == "cor", 1, 0),
           final = ifelse(final == "cor", 1, 0)) %>%
    gather(sameCue, probability, SC_joint_acc, OC_joint_acc) %>%
    mutate(sameCue = ifelse(sameCue == "SC_joint_acc", "yes", "no")) %>%
    left_join(y = raw_joint_RT, by = c("sameCue", "practice", "final")) %>%
    tbl_df()

  # Conditional Accuracy
  SC_CD <- SC_joint_acc[c("cor_cor", "inc_cor")]/abs((c(0,1) - practice_test$accuracy[practice_test$sameCue=="yes"]))
  OC_CD <- OC_joint_acc[c("cor_cor", "inc_cor")]/abs((c(0,1) - practice_test$accuracy[practice_test$sameCue=="no"]))

  CD_results <- cbind(as.data.frame(SC_CD), as.data.frame(OC_CD)) %>%
    mutate(practice = gsub("_cor", "", rownames(.))) %>%
    gather(sameCue, accuracy, SC_CD, OC_CD) %>%
    mutate(sameCue = ifelse(sameCue == "SC_CD", "yes", "no")) %>%
    mutate(sameCue, practice, accuracy)

  return(list(practice= practice_test, final = final_test,
              conditional = CD_results, joint = joint_results))
}


#' fitPCR
#'
#' @param PCRparams_obj
#' @param objective_fcn E.g., LB4L2_PCR
#' @param error_fcn
#' @param ...
#'
#' @return
#'
#' @import PCR
#' @export
#'
#' @examples

fitPCR <- function(free_parameters, PCRparams_obj, objective_fcn, error_fcn, ...) {

  PCRparams_obj <- update(PCRparams_obj, as.list(free_parameters))
  acc_param_vals <- PCRparams_obj$params[names(PCRparams_obj$params) %in% c("ER","LR","FR","FR2","TR","space","TC")]
  RT_param_vals <- PCRparams_obj$params[c("Tmin", "Tmax", "lambda")]

  if (any(sapply(acc_param_vals, function(x) x <= 0.01 || x >= .99))) {
    return(1000000)
  }

  if (any(sapply(RT_param_vals, function(x) x <= 0))) {
    return(1000000)
  }

  if (RT_param_vals$Tmin > RT_param_vals$Tmax) {
    return(1000000)
  }

  raw <- objective_fcn(PCRparams_obj, groups = list(...)$group)
  if (length(raw) > 1) {
    results <- lapply(raw, summary)
    results <- do.call(mapply, c(list(FUN = bind_rows), results , list(.id = "group")))
  } else {
    results <- summary(raw)
  }

  error <- error_fcn(results, ...)
  return(error$error)

}

#' LB4L2_PCR Error Function
#'
#' @param results
#' @param IV_obs
#' @param joint_obs
#' @param likelihood
#'
#' @return
#'
#' @import PCR
#' @importFrom tidyr gather spread unnest
#' @importFrom ks kde
#' @importFrom whoppeR binomialLL multinomialLL
#' @export
#'
#' @examples
LB4L2_PCR_erf <- function(results, IV_obs, joint_obs, likelihood = c("RT","accuracy","all"), ...) {

  likelihood <- match.arg(likelihood,  c("RT","accuracy","all"))
  error <- 0

  IV_pred <- results$final %>%
    select(group, practice, OCpractice, final_acc = accuracy,
           mean_p = proportion, mean_RT = medianRT, rawRTs = rawRTs) %>%
    rowwise() %>%
    mutate(rawRTs = list(round(rawRTs,1)),
           group = if(group == "group1") {"immediate"} else {"delay"})


  IV <- bind_rows(mutate(IV_obs, type = "obs"),
                  mutate(IV_pred, type = "pred", subject = IV_obs$subject[1]))

  if (likelihood %in% c("all","accuracy")) {
    binom_lik <- select(IV,group:mean_p,type) %>%
      filter(final_acc == 1) %>%
      spread(type, mean_p) %>%
      with(binomialLL(obs = obs, pred = pred, N = 20))
    error <- error + binom_lik
  }

  if (likelihood %in% c("all","RT")) {
    binom_RTerror <- select(IV,group:final_acc, mean_RT, type) %>%
      filter(final_acc == 1) %>%
      spread(type, mean_RT) %>%
      with(sum((obs-pred)^2))
    error <- error + binom_RTerror
  }
    # IV_density<- select(filter(IV, type == "pred"), -mean_p, -mean_RT, -type) %>%
    #   rowwise() %>%
    #   mutate(KD = list(density(rawRTs, bw = 1, from = .1, to = 8, n = 80)[c("x","y")]))
    # IV_density$KD <- lapply(IV_density$KD, function(k)  {
    #   data.frame(RT=round(k$x,1), density= k$y/sum(k$y))
    #   })
    # IV_density <- select(IV_density, -rawRTs) %>%
    #   unnest(KD)
    # uni_RT_lik <- left_join(unnest(select(filter(IV_obs, final_acc==1),
    #                                       -mean_p, -mean_RT, RT = rawRTs)),
    #                         IV_density,
    #                         by = c("practice", "OCpractice", "RT","group"))
    # uni_RT_lik <- sum(-log(uni_RT_lik$density))
    # error <- error + uni_RT_lik
  # }

  joint_pred <- results$joint %>%
    select(group, sameCue, practice1acc = practice, final_acc = final,
           joint_p = probability, rawRTs = raw_joint_RTs) %>%
    arrange(sameCue, practice1acc, final_acc) %>%
    rowwise() %>%
    mutate(group = if(group == "group1") {"immediate"} else {"delay"})

  joint <- bind_rows(mutate(joint_obs, type = "obs"),
                     mutate(joint_pred, type = "pred", subject = joint_obs$subject[1]))

  if (likelihood %in% c("all","accuracy")) {
    multinomial_lik <- select(joint, -contains("RT")) %>%
      spread(type, joint_p) %>%
      mutate(pred = replace(pred, pred==0, .Machine$double.xmin)) %>%
      with(multinomialLL(obs, pred, N = 20))
    error <- error + multinomial_lik
  }

  if (likelihood %in% c("all","RT")) {
    multinomial_RT <- select(joint, group:final_acc,rawRTs, type) %>%
      filter(final_acc == 1, practice1acc ==1) %>%
      rowwise() %>%
      summarise(group = group, type = type, practice1acc = practice1acc, final_acc = final_acc,
                prac = mean(rawRTs[,1]), delta = mean(rawRTs[,2] -rawRTs[,1]))

    error <- error + sum((multinomial_RT$prac[multinomial_RT$type == "obs"] - multinomial_RT$prac[multinomial_RT$type == "pred"])^2) +
      sum((multinomial_RT$delta[multinomial_RT$type == "obs"] - multinomial_RT$delta[multinomial_RT$type == "pred"])^2)

  }
    # x_axis_points <- expand.grid(seq(.1,8,by=.1), seq(.1,8,by=.1))
    # joint_density <- filter(joint, practice1acc == 1, final_acc ==1, type=="pred") %>%
    #   select(group:final_acc, rawRTs) %>%
    #   rowwise() %>%
    #   mutate(KD = list(ks::kde(rawRTs, H = matrix(c(1,0,0,1),2),  binned = TRUE,
    #                            eval.points = x_axis_points)))
    # joint_density$KD <- lapply(joint_density$KD, function(k){
    #   data.frame(pracRT = round(k$eval.points[[1]],1),
    #              finalRT = round(k$eval.points[[2]],1),
    #              density = k$estimate/sum(k$estimate))
    #   })
    #
    # joint_density <- select(joint_density, -KD) %>%
    #   rowwise() %>%
    #   mutate(rawRTs = list(setNames(as.data.frame(rawRTs), c("pracRT","finalRT"))),
    #          rawRTs = list(as.data.frame(lapply(rawRTs, round, 1)))) %>%
    #   unnest() %>%
    #   left_join(unnest(select(joint_density, -rawRTs)),
    #             c("group", "sameCue", "practice1acc", "final_acc", "pracRT", "finalRT"))
    # joint_RT_lik <- sum(-log(joint_density$density))
    # error <- error + joint_RT_lik
  # }

  if (likelihood %in% c("all","RT")) {
    return_data <- list(error = error, IV = list(IV), Joint = list(joint, multinomial_RT))
  } else {
    return_data <- list(error = error, IV = IV, Joint = joint)
  }

  return(return_data)
}

#' @export
#'
combine <- function(obj, practice = NA, final = NA, conditional = NA, joint = NA) {

}
